#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager


## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
## xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Notification Daemon
exec dunst &

## Launch Plank
## exec plank &

## Thunar Daemon
##exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &




## Restore Wallpaper
xrandr --output HDMI-0 --primary --mode 2560x1440 --scale 0.9 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1680x1050 --pos 2560x0 --rotate normal --output DP-0 --off --output DP-1 --off

exec ~/blucher_scripts/WalperRandomaser.sh &
## Launch Polybar or Tint2
polybar main &
polybar support &
## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## xfce4-settings daemon
##xfsettingsd &

## User Friendly Network Menu
#nm-applet --indicator &

## User Friendly Bluetooth Menu
#blueman-applet &

##exec /home/blucher/nekoray/nekoray -tray &
#exec AmneziaVPN -tray &
